// Code generated by protoc-gen-go. DO NOT EDIT.
// source: heartbeat.proto

/*
Package heartbeat is a generated protocol buffer package.

It is generated from these files:
	heartbeat.proto

It has these top-level messages:
	HeartBeat
	Location
	HeartBeats
*/
package heartbeat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Using Sequential ID not UUID. Potentially redesign.
type HeartBeat struct {
	Timestamp int64     `protobuf:"varint,1,opt,name=Timestamp,json=timestamp" json:"Timestamp,omitempty"`
	Location  *Location `protobuf:"bytes,2,opt,name=Location,json=location" json:"Location,omitempty"`
	UserID    int64     `protobuf:"varint,3,opt,name=UserID,json=userID" json:"UserID,omitempty"`
}

func (m *HeartBeat) Reset()                    { *m = HeartBeat{} }
func (m *HeartBeat) String() string            { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()               {}
func (*HeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HeartBeat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HeartBeat) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *HeartBeat) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

// Upon a stream most of these will not be filled at the time. They will be completed post process
type Location struct {
	Long     float64 `protobuf:"fixed64,1,opt,name=Long,json=long" json:"Long,omitempty"`
	Lat      float64 `protobuf:"fixed64,2,opt,name=Lat,json=lat" json:"Lat,omitempty"`
	City     string  `protobuf:"bytes,3,opt,name=City,json=city" json:"City,omitempty"`
	Country  string  `protobuf:"bytes,4,opt,name=Country,json=country" json:"Country,omitempty"`
	Address  string  `protobuf:"bytes,5,opt,name=Address,json=address" json:"Address,omitempty"`
	Address2 string  `protobuf:"bytes,6,opt,name=Address2,json=address2" json:"Address2,omitempty"`
	Zip      string  `protobuf:"bytes,7,opt,name=Zip,json=zip" json:"Zip,omitempty"`
	State    string  `protobuf:"bytes,8,opt,name=State,json=state" json:"State,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Location) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *Location) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Location) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *Location) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Location) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type HeartBeats struct {
	Heartbeats []*HeartBeat `protobuf:"bytes,1,rep,name=heartbeats" json:"heartbeats,omitempty"`
}

func (m *HeartBeats) Reset()                    { *m = HeartBeats{} }
func (m *HeartBeats) String() string            { return proto.CompactTextString(m) }
func (*HeartBeats) ProtoMessage()               {}
func (*HeartBeats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HeartBeats) GetHeartbeats() []*HeartBeat {
	if m != nil {
		return m.Heartbeats
	}
	return nil
}

func init() {
	proto.RegisterType((*HeartBeat)(nil), "heartbeat.HeartBeat")
	proto.RegisterType((*Location)(nil), "heartbeat.Location")
	proto.RegisterType((*HeartBeats)(nil), "heartbeat.HeartBeats")
}

func init() { proto.RegisterFile("heartbeat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x18, 0xc4, 0x65, 0x9c, 0xbf, 0x5f, 0x07, 0x90, 0xa9, 0x90, 0x85, 0x18, 0xa2, 0x4c, 0x99, 0x8a,
	0x14, 0x78, 0x01, 0x5a, 0x06, 0x90, 0x32, 0x19, 0x58, 0xd8, 0xdc, 0xd4, 0x2a, 0x96, 0xd2, 0x38,
	0xb2, 0xbf, 0x0e, 0xe1, 0xd9, 0x78, 0x38, 0x14, 0x27, 0x4d, 0xbb, 0xf9, 0xee, 0xf7, 0xe9, 0x4e,
	0x3a, 0xc3, 0xf5, 0x8f, 0x92, 0x16, 0xb7, 0x4a, 0xe2, 0xaa, 0xb3, 0x06, 0x0d, 0x4b, 0x67, 0x23,
	0xb7, 0x90, 0xbe, 0x0d, 0x62, 0xad, 0x24, 0xb2, 0x07, 0x48, 0x3f, 0xf5, 0x41, 0x39, 0x94, 0x87,
	0x8e, 0x93, 0x8c, 0x14, 0x54, 0xa4, 0x78, 0x32, 0xd8, 0x23, 0x24, 0x95, 0xa9, 0x25, 0x6a, 0xd3,
	0xf2, 0xab, 0x8c, 0x14, 0x8b, 0xf2, 0x76, 0x75, 0x4e, 0x3e, 0x21, 0x91, 0x34, 0xd3, 0x8b, 0xdd,
	0x41, 0xf4, 0xe5, 0x94, 0x7d, 0x7f, 0xe5, 0xd4, 0x67, 0x45, 0x47, 0xaf, 0xf2, 0x3f, 0x72, 0x4e,
	0x62, 0x0c, 0x82, 0xca, 0xb4, 0x7b, 0x5f, 0x47, 0x44, 0xd0, 0x98, 0x76, 0xcf, 0x6e, 0x80, 0x56,
	0x12, 0x7d, 0x09, 0x11, 0xb4, 0x91, 0x38, 0x5c, 0x6d, 0x34, 0xf6, 0x3e, 0x28, 0x15, 0x41, 0xad,
	0xb1, 0x67, 0x1c, 0xe2, 0x8d, 0x39, 0xb6, 0x68, 0x7b, 0x1e, 0x78, 0x3b, 0xae, 0x47, 0x39, 0x90,
	0x97, 0xdd, 0xce, 0x2a, 0xe7, 0x78, 0x38, 0x12, 0x39, 0x4a, 0x76, 0x0f, 0xc9, 0x44, 0x4a, 0x1e,
	0x79, 0x94, 0x4c, 0xa8, 0x1c, 0x5a, 0xbf, 0x75, 0xc7, 0x63, 0x6f, 0xd3, 0x5f, 0xdd, 0xb1, 0x25,
	0x84, 0x1f, 0x28, 0x51, 0xf1, 0xc4, 0x7b, 0xa1, 0x1b, 0x44, 0xbe, 0x06, 0x98, 0x27, 0x73, 0xec,
	0x19, 0x60, 0x1e, 0xc1, 0x71, 0x92, 0xd1, 0x62, 0x51, 0x2e, 0x2f, 0x76, 0x99, 0x4f, 0xc5, 0xc5,
	0xdd, 0x36, 0xf2, 0x1f, 0xf1, 0xf4, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x27, 0x49, 0x9c, 0x54, 0x9b,
	0x01, 0x00, 0x00,
}
