// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tracker/proto/heartbeat/heartbeat.proto

/*
Package heartbeat is a generated protocol buffer package.

It is generated from these files:
	tracker/proto/heartbeat/heartbeat.proto

It has these top-level messages:
	Heartbeat
	HeartbeatTrack
*/
package heartbeat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import location "tracker/proto/location"
import uuid "tracker/proto/uuid"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO:Using Sequential ID not UUID. Potentially redesign. Model will be time index
type Heartbeat struct {
	Timestamp int64              `protobuf:"varint,1,opt,name=Timestamp,json=timestamp" json:"Timestamp,omitempty"`
	Offset    int32              `protobuf:"varint,2,opt,name=Offset,json=offset" json:"Offset,omitempty"`
	Location  *location.Location `protobuf:"bytes,3,opt,name=Location,json=location" json:"Location,omitempty"`
	UserId    int64              `protobuf:"varint,4,opt,name=UserId,json=userId" json:"UserId,omitempty"`
	Longitude float64            `protobuf:"fixed64,5,opt,name=Longitude,json=longitude" json:"Longitude,omitempty"`
	Latitude  float64            `protobuf:"fixed64,6,opt,name=Latitude,json=latitude" json:"Latitude,omitempty"`
	Altitude  float64            `protobuf:"fixed64,7,opt,name=Altitude,json=altitude" json:"Altitude,omitempty"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Heartbeat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Heartbeat) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Heartbeat) GetLocation() *location.Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Heartbeat) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Heartbeat) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Heartbeat) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Heartbeat) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

type HeartbeatTrack struct {
	Uuid       *uuid.UUID   `protobuf:"bytes,1,opt,name=Uuid,json=uuid" json:"Uuid,omitempty"`
	Heartbeats []*Heartbeat `protobuf:"bytes,2,rep,name=Heartbeats,json=heartbeats" json:"Heartbeats,omitempty"`
	Starttime  int64        `protobuf:"varint,3,opt,name=Starttime,json=starttime" json:"Starttime,omitempty"`
	UserId     int64        `protobuf:"varint,4,opt,name=UserId,json=userId" json:"UserId,omitempty"`
}

func (m *HeartbeatTrack) Reset()                    { *m = HeartbeatTrack{} }
func (m *HeartbeatTrack) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatTrack) ProtoMessage()               {}
func (*HeartbeatTrack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HeartbeatTrack) GetUuid() *uuid.UUID {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *HeartbeatTrack) GetHeartbeats() []*Heartbeat {
	if m != nil {
		return m.Heartbeats
	}
	return nil
}

func (m *HeartbeatTrack) GetStarttime() int64 {
	if m != nil {
		return m.Starttime
	}
	return 0
}

func (m *HeartbeatTrack) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*Heartbeat)(nil), "heartbeat.Heartbeat")
	proto.RegisterType((*HeartbeatTrack)(nil), "heartbeat.HeartbeatTrack")
}

func init() { proto.RegisterFile("tracker/proto/heartbeat/heartbeat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x6a, 0xf3, 0x30,
	0x10, 0x85, 0x51, 0x9c, 0xf8, 0xb7, 0x26, 0xf0, 0x2f, 0x44, 0x29, 0x22, 0xb4, 0xc5, 0x04, 0x4a,
	0xbd, 0x72, 0x20, 0xed, 0x05, 0x0a, 0x5d, 0x34, 0x10, 0x28, 0xa8, 0xf1, 0x01, 0x94, 0x58, 0x69,
	0x4d, 0x9d, 0x28, 0x48, 0xe3, 0xdb, 0xf4, 0x6e, 0xbd, 0x4a, 0x91, 0x6c, 0x29, 0x64, 0xd1, 0x8d,
	0x99, 0xf7, 0x3e, 0x8f, 0x46, 0xf3, 0x04, 0x0f, 0x68, 0xe4, 0xee, 0x4b, 0x99, 0xc5, 0xc9, 0x68,
	0xd4, 0x8b, 0x4f, 0x25, 0x0d, 0x6e, 0x95, 0xc4, 0x73, 0x55, 0x7a, 0xc2, 0x68, 0x34, 0x66, 0xf7,
	0x97, 0x3d, 0xad, 0xde, 0x49, 0x6c, 0xf4, 0x31, 0x16, 0x7d, 0xc7, 0xec, 0xf6, 0xf2, 0xb7, 0xae,
	0x6b, 0x6a, 0xff, 0xe9, 0xf1, 0xfc, 0x87, 0x00, 0x7d, 0x0d, 0x67, 0xb2, 0x1b, 0xa0, 0x9b, 0xe6,
	0xa0, 0x2c, 0xca, 0xc3, 0x89, 0x93, 0x9c, 0x14, 0x89, 0xa0, 0x18, 0x0c, 0x76, 0x0d, 0xe9, 0xdb,
	0x7e, 0x6f, 0x15, 0xf2, 0x51, 0x4e, 0x8a, 0x89, 0x48, 0xb5, 0x57, 0xac, 0x84, 0x6c, 0x3d, 0x0c,
	0xe5, 0x49, 0x4e, 0x8a, 0xe9, 0x92, 0x95, 0xf1, 0x16, 0x81, 0x88, 0x2c, 0x58, 0xee, 0x9c, 0xca,
	0x2a, 0xb3, 0xaa, 0xf9, 0xd8, 0x8f, 0x48, 0x3b, 0xaf, 0xdc, 0xf4, 0xb5, 0x3e, 0x7e, 0x34, 0xd8,
	0xd5, 0x8a, 0x4f, 0x72, 0x52, 0x10, 0x41, 0xdb, 0x60, 0xb0, 0x19, 0x64, 0x6b, 0x89, 0x3d, 0x4c,
	0x3d, 0xcc, 0xda, 0x41, 0x3b, 0xf6, 0xdc, 0x0e, 0xec, 0x5f, 0xcf, 0xe4, 0xa0, 0xe7, 0xdf, 0x04,
	0xfe, 0xc7, 0x0d, 0x37, 0x2e, 0x0c, 0x76, 0x07, 0xe3, 0xaa, 0x6b, 0x6a, 0xbf, 0xe1, 0x74, 0x09,
	0xa5, 0xcf, 0xa3, 0xaa, 0x56, 0x2f, 0x62, 0xec, 0x4a, 0xf6, 0x04, 0x10, 0x3b, 0x2c, 0x1f, 0xe5,
	0x49, 0x31, 0x5d, 0x5e, 0x95, 0xe7, 0xb7, 0x88, 0x50, 0x40, 0x34, 0xad, 0xbb, 0xfe, 0x3b, 0x4a,
	0x83, 0x2e, 0x30, 0x9f, 0x43, 0x22, 0xa8, 0x0d, 0xc6, 0x5f, 0x4b, 0x6f, 0x53, 0xff, 0x0e, 0x8f,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x00, 0x25, 0xff, 0x05, 0x03, 0x02, 0x00, 0x00,
}
