// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Config
	USER_CONFIG
	DB_CONFIG
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	DB   *DB_CONFIG   `protobuf:"bytes,1,opt,name=DB,json=dB" json:"DB,omitempty"`
	USER *USER_CONFIG `protobuf:"bytes,2,opt,name=USER,json=uSER" json:"USER,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetDB() *DB_CONFIG {
	if m != nil {
		return m.DB
	}
	return nil
}

func (m *Config) GetUSER() *USER_CONFIG {
	if m != nil {
		return m.USER
	}
	return nil
}

type USER_CONFIG struct {
	Name      string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=Address,json=address" json:"Address,omitempty"`
	Address2  string `protobuf:"bytes,3,opt,name=Address2,json=address2" json:"Address2,omitempty"`
	Last_Seen int64  `protobuf:"varint,4,opt,name=Last_Seen,json=lastSeen" json:"Last_Seen,omitempty"`
}

func (m *USER_CONFIG) Reset()                    { *m = USER_CONFIG{} }
func (m *USER_CONFIG) String() string            { return proto.CompactTextString(m) }
func (*USER_CONFIG) ProtoMessage()               {}
func (*USER_CONFIG) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *USER_CONFIG) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *USER_CONFIG) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *USER_CONFIG) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *USER_CONFIG) GetLast_Seen() int64 {
	if m != nil {
		return m.Last_Seen
	}
	return 0
}

type DB_CONFIG struct {
	Type     string `protobuf:"bytes,1,opt,name=Type,json=type" json:"Type,omitempty"`
	User     string `protobuf:"bytes,2,opt,name=User,json=user" json:"User,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *DB_CONFIG) Reset()                    { *m = DB_CONFIG{} }
func (m *DB_CONFIG) String() string            { return proto.CompactTextString(m) }
func (*DB_CONFIG) ProtoMessage()               {}
func (*DB_CONFIG) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DB_CONFIG) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DB_CONFIG) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *DB_CONFIG) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "config.Config")
	proto.RegisterType((*USER_CONFIG)(nil), "config.USER_CONFIG")
	proto.RegisterType((*DB_CONFIG)(nil), "config.DB_CONFIG")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0xb3, 0xd1, 0x8c, 0xed, 0xe1, 0xc5, 0xe7, 0xa5, 0xd1, 0x0b, 0xee, 0x22, 0x27, 0x0e,
	0xf3, 0x2f, 0x70, 0x80, 0xc6, 0xc4, 0x80, 0xe9, 0xe0, 0x4c, 0xaa, 0x7b, 0x1a, 0x13, 0xd9, 0x96,
	0xbe, 0x12, 0xc3, 0x7f, 0x6f, 0x5a, 0xba, 0x85, 0x5b, 0xbf, 0x3f, 0xf2, 0xfd, 0x34, 0x0f, 0xae,
	0x3e, 0xdb, 0xe6, 0xeb, 0xe7, 0x7b, 0xde, 0x99, 0xd6, 0xb6, 0x98, 0x9c, 0x55, 0xbe, 0x85, 0x64,
	0xe1, 0x5f, 0x78, 0x0f, 0xf1, 0xb2, 0x94, 0xd1, 0x34, 0x9a, 0x4d, 0x8a, 0xeb, 0x79, 0x28, 0x2f,
	0xcb, 0xfd, 0x62, 0xb3, 0x7e, 0x7e, 0x7d, 0x51, 0x71, 0x5d, 0xe2, 0x03, 0x88, 0x5d, 0xb5, 0x52,
	0x32, 0xf6, 0xa5, 0x9b, 0xbe, 0xe4, 0xbc, 0xbe, 0x26, 0x8e, 0xd5, 0x4a, 0xe5, 0x16, 0x26, 0x17,
	0x26, 0x22, 0x88, 0xb5, 0x3e, 0x90, 0x1f, 0xcf, 0x94, 0x68, 0xf4, 0x81, 0x50, 0xc2, 0xf8, 0xa9,
	0xae, 0x0d, 0x31, 0xfb, 0xb9, 0x4c, 0x8d, 0xf5, 0x59, 0xe2, 0x2d, 0xa4, 0x21, 0x29, 0xe4, 0xc8,
	0x47, 0x69, 0x88, 0x0a, 0xbc, 0x83, 0xec, 0x4d, 0xb3, 0xdd, 0x57, 0x44, 0x8d, 0x14, 0xd3, 0x68,
	0x36, 0x52, 0xe9, 0xaf, 0x66, 0xeb, 0x74, 0xbe, 0x81, 0x6c, 0xf8, 0xaf, 0x63, 0x6e, 0x4f, 0xdd,
	0xc0, 0xb4, 0xa7, 0x8e, 0x9c, 0xb7, 0x63, 0x32, 0x01, 0x28, 0x8e, 0x4c, 0xc6, 0xd1, 0xde, 0x35,
	0xf3, 0x5f, 0x6b, 0xea, 0x9e, 0xd6, 0x05, 0xfd, 0x91, 0xf8, 0x5b, 0x3d, 0xfe, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x53, 0x61, 0x63, 0xc4, 0x3b, 0x01, 0x00, 0x00,
}
