// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location.proto

/*
Package location is a generated protocol buffer package.

It is generated from these files:
	location.proto

It has these top-level messages:
	Location
*/
package location

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Location is the seralized form. Not used for querying because it is slow.
type Location struct {
	Long     float64 `protobuf:"fixed64,1,opt,name=Long,json=long" json:"Long,omitempty"`
	Lat      float64 `protobuf:"fixed64,2,opt,name=Lat,json=lat" json:"Lat,omitempty"`
	Altitude float64 `protobuf:"fixed64,3,opt,name=Altitude,json=altitude" json:"Altitude,omitempty"`
	City     string  `protobuf:"bytes,4,opt,name=City,json=city" json:"City,omitempty"`
	Country  string  `protobuf:"bytes,5,opt,name=Country,json=country" json:"Country,omitempty"`
	Address  string  `protobuf:"bytes,6,opt,name=Address,json=address" json:"Address,omitempty"`
	Address2 string  `protobuf:"bytes,7,opt,name=Address2,json=address2" json:"Address2,omitempty"`
	Zip      string  `protobuf:"bytes,8,opt,name=Zip,json=zip" json:"Zip,omitempty"`
	State    string  `protobuf:"bytes,9,opt,name=State,json=state" json:"State,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Location) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *Location) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Location) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Location) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *Location) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Location) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterType((*Location)(nil), "location.Location")
}

func init() { proto.RegisterFile("location.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xb1, 0x8a, 0x84, 0x30,
	0x10, 0x40, 0xc9, 0x25, 0x6a, 0x4c, 0x71, 0x1c, 0xe1, 0x8a, 0xe1, 0x2a, 0xb9, 0xca, 0xea, 0x0a,
	0xef, 0x0b, 0xc4, 0xd6, 0xca, 0xeb, 0xae, 0xcb, 0xaa, 0x48, 0x20, 0x24, 0xa2, 0x63, 0xe1, 0x7e,
	0xe9, 0x7e, 0xce, 0x92, 0x89, 0xdb, 0xe5, 0xbd, 0x07, 0x99, 0x19, 0xf5, 0xee, 0xc2, 0x68, 0xd0,
	0x06, 0xff, 0xb3, 0x6e, 0x01, 0x83, 0x96, 0x2f, 0xfe, 0x7e, 0x30, 0x25, 0xfb, 0x0b, 0xb4, 0x56,
	0xa2, 0x0f, 0x7e, 0x01, 0x56, 0xb1, 0x9a, 0x0d, 0xc2, 0x05, 0xbf, 0xe8, 0x0f, 0xc5, 0x7b, 0x83,
	0xf0, 0x46, 0x8a, 0x3b, 0x83, 0xfa, 0x4b, 0xc9, 0xd6, 0xa1, 0xc5, 0x63, 0x9a, 0x81, 0x93, 0x96,
	0xe6, 0xe2, 0xf8, 0x43, 0x67, 0xf1, 0x04, 0x51, 0xb1, 0xba, 0x1c, 0xc4, 0x68, 0xf1, 0xd4, 0xa0,
	0x8a, 0x2e, 0x1c, 0x1e, 0xb7, 0x13, 0x32, 0xd2, 0xc5, 0x98, 0x30, 0x96, 0x76, 0x9a, 0xb6, 0x79,
	0xdf, 0x21, 0x4f, 0xc5, 0x24, 0xa4, 0x19, 0xe9, 0xd9, 0x40, 0x41, 0x49, 0x5e, 0xa9, 0x89, 0x1b,
	0xfd, 0xdb, 0x15, 0x24, 0x69, 0x7e, 0xb7, 0xab, 0xfe, 0x54, 0xd9, 0x1f, 0x1a, 0x9c, 0xa1, 0x24,
	0x97, 0xed, 0x11, 0x6e, 0x39, 0xdd, 0xfa, 0xfb, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x81, 0x82, 0xd0,
	0x22, 0xfd, 0x00, 0x00, 0x00,
}
